name: $(Build.BuildId)
queue: Hosted Linux Preview
trigger:
- master
steps:

- bash: |
   pip install setuptools
   pip install awscli
   export AWS_SECRET_ACCESS_KEY=$(AWS_SECRET_ACCESS_KEY)
   chmod +x ./pipeline.sh
   ./pipeline.sh $(Build.BuildId) $(System.DefaultWorkingDirectory)
  displayName: Container registry service pipeline Bash Script
  enabled: true

- task: PublishBuildArtifacts@1
  displayName: "Publish Artifact: manifests"
  inputs:
    PathtoPublish: k8s
    ArtifactName: manifests