apiVersion: v1
kind: Service
metadata:
  labels:
    app: container-registry-service
  name: container-registry-service
  namespace: $(kubernetes-namespace)
  annotations:
    prometheus.io/scrape: 'true'
spec:
  ports:
  - name: external
    port: 80
    targetPort: web
  selector:
    app: container-registry-service
  type: ClusterIP